name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "github/workflows/**"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: crate-ci/typos@master

  basedpyright:
    name: BasedPyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: 3.12
          version: "latest"

      - name: Install Dependencies
        run: uv sync

      - name: Static typing check
        run: uvx basedpyright

  test:
    name: Coverage
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      # group: test-coverage-${{ github.ref }}-${{ matrix.python-version }}-${{ matrix.os }}
      group: coverage-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        # pydantic-version: ["v1", "v2"]

    env:
      # OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      UV_NO_SYNC: 1

    steps:
      - uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: "latest"

      - name: Install Dependencies with test group
        run: uv sync --no-dev --locked

      - name: Run Pytest
        run: uv run poe test

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          env_vars: PYTHON
          use_oidc: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          env_vars: PYTHON
          use_oidc: true